#!/bin/sh
'''exec' "/Users/kova/Desktop/Kova/claude/Claude trading/venv/bin/python3.12" "$0" "$@"
' '''
import sys
from fontTools.merge import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
